[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 921600

build_flags = 
    -D CORE_DEBUG_LEVEL=3
    -D ARDUINOJSON_USE_LONG_LONG=1

lib_deps =
    bblanchon/ArduinoJson @ ^7.0.4
    knolleary/PubSubClient @ ^2.8
    bogde/HX711 @ ^0.7.5
    adafruit/DHT sensor library @ ^1.4.6
    adafruit/Adafruit Unified Sensor @ ^1.1.14
    adafruit/Adafruit BME280 Library @ ^2.2.4
    kosme/arduinoFFT @ ^2.0.4
